DELIMITER $$

CREATE FUNCTION CHECK_JOB_PROFILE(EXPERIENCE INT)
RETURNS VARCHAR(30)
DETERMINISTIC
BEGIN
    DECLARE PROFILE VARCHAR(30);
    IF EXPERIENCE <= 2 THEN
        SET PROFILE = 'JUNIOR DATA SCIENTIST';
    ELSEIF EXPERIENCE <= 5 THEN
        SET PROFILE = 'ASSOCIATE DATA SCIENTIST';
    ELSEIF EXPERIENCE <= 10 THEN
        SET PROFILE = 'SENIOR DATA SCIENTIST';
    ELSEIF EXPERIENCE <= 12 THEN
        SET PROFILE = 'LEAD DATA SCIENTIST';
    ELSE
        SET PROFILE = 'MANAGER';
    END IF;
    RETURN PROFILE;
END $$

DELIMITER ;

SELECT EMP_ID, FIRST_NAME, LAST_NAME, ROLE, EXP,
       CHECK_JOB_PROFILE(EXP) AS EXPECTED_PROFILE
FROM data_science_team;
